"""Initial schema baseline

Revision ID: 1fc184ce3982
Revises: 
Create Date: 2026-09-23 22:42:37.933794

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '1fc184ce3982'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
